export const LOGO_URL ="https://app.logo.com/view/logo_b05d647a-d9c9-4d03-9dbc-13c349e469a9"
export const RES_DATA ="https://www.swiggy.com/dapi/restaurants/list/v5?lat=17.473388&lng=78.488053&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING"
export const IMG_URL = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/"
export const CAROUSEL_IMG ="https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_850,h_504/"
export const MENU_API="https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=17.473388&lng=78.488053&restaurantId="